// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const ADMIN_SAVE_TOKEN = 'ADMIN_SAVE_TOKEN'
export const ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'
export const ADMIN_FETCH_USER_SUCCESS = 'ADMIN_FETCH_USER_SUCCESS'
export const ADMIN_FETCH_USER_FAILURE = 'ADMIN_FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
